'use strict';var $x={TAB:0,Ki:1,em:2},ay=function(a){xb("MediaRouter.CastStreaming.Start.Success",a,$x)};var by=db("mr.mirror.cast.LogUploader"),dy=function(a,b,c){cy("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},cy=function(a,b,c,d){if(0==b.size)by.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);uw("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;Ew(a)?(b=Fw(a),by.info("Upload to Crash succeeded: "+
b)):by.info("Upload to Crash failed. HTTP status: "+a.Ua());d&&d(b)},"POST",e,void 0,3E4)}};var ey=function(){this.b=0;Yi(this)},gy=function(){fy||(fy=new ey);return fy},hy=function(){var a=gy(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&c&&d-a.b<c?!1:Math.random()<b.fraction};ey.prototype.ua=function(){return"mirror.cast.LogUtils"};ey.prototype.Ra=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};ey.prototype.Va=function(){var a=Wi(this);this.b=a&&a.lastAutoSubmitMillis||0};var fy=null;db("mr.mirror.cast.LogUtils");var iy={hu:"OFFER",Mq:"ANSWER",Du:"PRESENTATION",qs:"GET_STATUS",vv:"STATUS_RESPONSE",ps:"GET_CAPABILITIES",gr:"CAPABILITIES_RESPONSE",ev:"RPC"};var jy=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},my=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;ky(JSON.parse(a),function(a){b=ly(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},ly=function(a){var b=new jy;null!=a.sessionId&&(b.sessionId=String(a.sessionId));ny(a.seqNum,function(a){b.f=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=la(Object.keys(iy)),e=d.next();!e.done;e=d.next())if(iy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(xa(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}ky(a.error,function(a){b.error=oy(a)},function(){throw Error('"error" must be an Object');});ky(a.answer,function(a){b.b=py(a)},function(){throw Error('"answer" must be an Object');});ky(a.status,function(a){b.status=qy(a)},function(){throw Error('"status" must be an Object');
});ky(a.capabilities,function(a){b.capabilities=ry(a)},function(){throw Error('"capabilities" must be an Object');});return b},ky=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},ny=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},sy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},ty=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},uy=function(){this.j=null;this.b=[];this.f=
[];this.h=this.g=this.l=null},py=function(a){var b=new uy;ny(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});sy(a.sendIndexes,function(a){b.b=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});sy(a.ssrcs,function(a){b.f=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.l=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.h=String(a.castMode));
return b},vy=function(){this.details=this.description=this.code=null},oy=function(a){var b=new vy;ny(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));ky(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},wy=function(){this.f=this.b=null},qy=function(a){var b=new wy;ny(a.wifiSnr,function(a){b.b=a},function(){throw Error('"status.wifiSnr" must be a number');
});sy(a.wifiSpeed,function(a){b.f=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},xy=function(){this.f=this.b=null},ry=function(a){var b=new xy;ty(a.mediaCaps,function(a){b.b=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.f=a.map(function(a){var b;ky(a,function(a){b=yy(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},zy=function(){this.h=this.A=this.l=this.j=this.s=this.b=this.o=this.f=this.initDataTypes=this.g=null},yy=function(a){var b=new zy;"keySystemName"in a&&(b.g=String(a.keySystemName));ty(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});ty(a.codecs,function(a){b.f=a},function(){throw Error('"capabilities.codecs" must be an array');});ty(a.secureCodecs,function(a){b.o=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});ty(a.audioRobustness,function(a){b.b=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});ty(a.videoRobustness,function(a){b.s=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.l=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.A=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var Ay=function(a){this.m=db("mr.mirror.cast.MessageDispatcher");this.g=a;this.b=null;this.f=new Map;this.h=0},By=function(a,b,c){if(a.f.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.f.set(b,c);a.h=0;jb(a.m,"Added subscriber for "+b+"-type messages.");a.b||(a.b=Uw(a.g),a.b.onMessage=a.j.bind(a))},Cy=function(a,b){a.f.delete(b)&&jb(a.m,function(){return"Removed subscriber of "+b+"-type messages."});0==a.f.size&&a.b&&(a.b.Pa(),a.b=null)};
Ay.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Dy=function(a,b,c,d,e){var f=null,h=function(){Cy(a,c);null!=f&&(clearTimeout(f),f=null)};try{By(a,c,function(a){e(a)&&h()})}catch(k){e(null,k);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Ay.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=my(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.f.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.h?v(this.m,b):jb(this.m,b);++this.h}};var Ey=function(){this.b=Promise.resolve(1)},Gy=function(a,b,c){return Fy(a,function(a){return a==b},c)},Hy=function(a,b){var c=[3,4];return Fy(a,function(a){return-1!=c.indexOf(a)},b)},Iy=function(a,b){a.b=a.b.catch(function(){return 1});return Fy(a,function(){return!0},b)},Fy=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.b=a.b.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Jy(a);try{var h=c(f)}catch(r){h=
Promise.reject(r)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.b)throw Error("A prior operation that started at "+(a+" did not complete."));return f.b})},function(a){e(a);throw a;});return f},Jy=function(a){this.f=a;this.b=null},Ky=function(a,b){a.b="number"===typeof b?b:a.f};var Ly=chrome.cast.streaming,Ny=function(a,b,c,d,e){this.R=a.sessionId;this.s=a.Qf;this.ja=a.Zd;this.h=b;this.D=c;this.C=d;this.K=My(e,"onAnswer",this.s);this.L=My(e,"onSessionStop",this.s);this.m=db("mr.mirror.cast.StreamingLaunchWorkflow");this.w=new Ey;this.A=this.B=this.o=this.f=this.b=this.l=this.j=this.g=null};
Ny.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Oy,f=b instanceof Oy;(e&&b&&!f||f&&a&&!e)&&Eb("Mixing remoting and non-remoting tracks");return Gy(this.w,1,function(e){d.g=a;d.j=b;d.l=c;d.m.info(function(){return"Launching streaming for "+Py(d)+" "+("to a "+d.ja+".")});return Qy(d).then(d.F.bind(d)).then(function(a){return Ry(d,a).then(function(b){d.K();var c=Sy(d,b,a);d.b=Ty(d,d.b,c);d.f=Ty(d,d.f,c);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.B=!!b.g;d.A=function(a,b){a==d.b?d.l.Qd("Audio stream (id="+a+") error: "+b):a==d.f&&d.l.Qd("Video stream (id="+a+") error: "+b)};Ly.rtpStream.onError.addListener(d.A);return Uy(d,b,c)})}).then(function(){d.m.info(function(){return"Launched streaming for "+Py(d)});d.l.jf(d);Ky(e,2);return{vn:d.b,mq:d.f}})})};
Ny.prototype.stop=function(){var a=this;return Iy(this.w,function(b){if(!a.g&&!a.j)return Ky(b,1),Promise.resolve();a.m.info(function(){return"Stopping streaming for "+Py(a)+"."});a.A&&(Ly.rtpStream.onError.removeListener(a.A),a.A=null);if(a.l){var c=a.l.Tf();a.l=null}else c=Promise.resolve();return c.then(function(){a.b&&(Ly.rtpStream.stop(a.b),Ly.rtpStream.destroy(a.b),a.b=null);a.f&&(Ly.rtpStream.stop(a.f),Ly.rtpStream.destroy(a.f),a.f=null);a.o&&(Ly.udpTransport.destroy(a.o),a.o=null);a.L();a.m.info(function(){return"Stopped streaming for "+
Py(a)+"."});a.g=null;a.j=null;Ky(b,1)})})};
var Vy=function(a,b){var c=JSON.stringify(b);return Promise.all([a.b&&new Promise(function(b){return Ly.rtpStream.getRawEvents(a.b,c,b)}),a.f&&new Promise(function(b){return Ly.rtpStream.getRawEvents(a.f,c,b)})]).catch(function(b){a.m.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},Wy=function(a){return Promise.all([a.b&&new Promise(function(b){return Ly.rtpStream.getStats(a.b,b)}),a.f&&
new Promise(function(b){return Ly.rtpStream.getStats(a.f,b)})]).catch(function(b){a.m.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[].concat([{}],xa(a.filter(function(a){return!!a}))))})},Py=function(a){if(a.g&&a.j)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.g instanceof Oy||a.j instanceof Oy?b+"remoting":b+"streaming"},Qy=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(Ly.rtpStream.destroy(c),c=null);e&&!a.j&&(Ly.rtpStream.destroy(e),e=null);a.m.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.b=c;a.f=e;a.o=f;b()};a.g instanceof Oy||a.j instanceof Oy?Ly.session.create(null,null,c):Ly.session.create(a.g,a.j,c)})};
Ny.prototype.F=function(){for(var a=Xg(),b=Xg(),c=[],d=la([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,h=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,r=la(Ly.rtpStream.getSupportedParams(e)),y=r.next();!y.done;y=r.next())y=y.value,y.payload.payloadType=h,y.payload.maxLatency=this.h.maxLatencyMillis,y.payload.minLatency=this.h.minLatencyMillis,y.payload.animatedLatency=this.h.animatedLatencyMillis,y.payload.ssrc=
k,y.payload.clockRate=m,y.payload.aesKey=a,y.payload.aesIvMask=b,f?(y.payload.channels=2,y.payload.maxBitrate=this.h.audioBitrate,y.payload.maxFrameRate=100):(y.payload.minBitrate=this.h.minVideoBitrate,y.payload.maxBitrate=this.h.maxVideoBitrate,y.payload.maxFrameRate=this.h.maxFrameRate),c.push(new Xy(e,y));return c};
var Ty=function(a,b,c){b&&!c.some(function(a){return a.Pe==b})&&(v(a.m,"Destroying RTP stream not selected by the receiver: id="+b),Ly.rtpStream.destroy(b),b=null);return b},Ry=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,k={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.h.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.h.dscpEnabled&&(k.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.h.maxWidth,height:a.h.maxHeight}]});e.push(k)}var m=a.g instanceof Oy||a.j instanceof Oy?"remoting":"mirroring",r={type:"OFFER",sessionId:a.R,seqNum:gl(a.D),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.m.info(function(){return"Sending OFFER message: "+JSON.stringify(r)});Dy(a.C,r,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.b){if(b.f!=r.seqNum)return v(a.m,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.b.h)&&e!=m||!e&&"mirroring"!=m)&&a.m.error("Expected receiver to ANSWER with castMode="+m+", but got: "+e);jb(a.m,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},Sy=function(a,b,c){if(b.b.length!=b.f.length)return a.m.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.b.length;e={candidate:e.candidate},++f){var h=b.b[f];if(0>h||h>=
c.length)return a.m.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.Pe==a.candidate.Pe}}(e)))return a.m.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.f[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.m.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},Uy=function(a,b,c){var d=null,e=function(){d&&(Ly.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.j||2344;a.m.info(function(){return"Starting RTP streams to receiver at "+(a.s+":"+f)+(" for selected offers: "+JSON.stringify(c))});var m=a.o||-1;a.h.dscpEnabled&&(a.m.info("Enabled DSCP in sender."),Ly.udpTransport.setOptions(m,{DSCP:!0}));Ly.udpTransport.setDestination(m,{address:a.s,port:f});var r=new Set(c.map(function(a){return a.Pe}));
d=function(a){r.delete(a);0==r.size&&e()};Ly.rtpStream.onStarted.addListener(d);m=la(c);for(var y=m.next();!y.done;y=m.next())y=y.value,Ly.rtpStream.toggleLogging(y.Pe,a.h.enableLogging),Ly.rtpStream.start(y.Pe,y.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},My=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.m.error("Error from testHooks."+b,e)}}:function(){}},Xy=function(a,b){this.Pe=
a;this.params=b},Oy=function(){};var $y=function(a,b,c,d,e,f){this.A=a;this.C=Yy(b,this.A.hc);this.D=new Ny(this.A.hc,c,d,e,f);this.B=e;this.j=new Ey;this.h=new Zy;this.w=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.m=db("mr.mirror.cast.MediaRemoter");this.s=this.b=this.l=this.g=this.F=null;this.f=!0;this.o=this.R.bind(this)},cz=function(a,b,c){return Gy(a.j,1,function(d){a.F=b;a.g=c;var e=a.w.createInterfacePtrAndBind();a.w.setConnectionErrorHandler(function(){a.m.info("Remoter mojo pipe connection error.");az(a)});
a.b=new mojo.MirrorServiceRemotingSourcePtr;var f=og(a.A.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+a.A.mediaSource);a.m.info("Connecting remoter to browser: tabId="+f);(Wf.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(a.b));a.b.ptr.setConnectionErrorHandler(function(){a.m.info("RemotingSource mojo pipe connection error.");az(a)});return bz(a).then(function(){if(a.f)a.b.onSinkAvailable(a.C);Ky(d,2)})})},az=function(a){return Iy(a.j,
function(b){a.b&&(a.b.ptr.reset(),a.b=null);var c=a.l;a.l=null;a.g=null;a.F=null;a.w.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.o);return new Promise(function(d){window.setTimeout(function(){dz(a).then(function(){Ky(b,1);d();c&&c()})},250)})})};$y.prototype.Lp=function(a){ez(this.h,a)};$y.prototype.sendMessageToSink=$y.prototype.Lp;$y.prototype.jf=function(a){this.g&&this.g.jf(a)};
$y.prototype.Tf=function(){return this.g?this.g.Tf():Promise.resolve()};$y.prototype.Qd=function(a,b){this.m.error("Error during streaming: "+a,b);if(this.b)this.b.onError();az(this)};
$y.prototype.start=function(){var a=this,b=!1;this.m.info(function(){b=!0;return"Starting next media remoting session."});b&&fz(this.h,function(b){return a.m.info(b)});gz(this.h);Gy(this.j,2,function(b){return(0,a.F)().then(function(c){a.l=c;By(a.B,"RPC",function(b){if(b.rpc){var c=a.h;b=b.rpc;c.l&&(++c.A,c.f+=b.length,c.l(b))}});Ky(b,3)}).catch(function(c){return dz(a).then(function(){Ky(b);throw c;})})}).then(function(){a.m.info("Remoting started successfully.")}).catch(function(b){a.m.error("Failed to start remoting",
b);a.b.onError()})};$y.prototype.start=$y.prototype.start;
$y.prototype.cq=function(a,b){var c=this;return Gy(this.j,3,function(d){return c.D.start(a?new Oy:null,b?new Oy:null,c).then(function(a){hz(c.h,function(a){return c.B.sendMessage(a)},function(a){c.b.onMessageFromSink(a)});Ky(d,4);return{audio_stream_id:a.vn||-1,video_stream_id:a.mq||-1}}).catch(function(a){return dz(c).then(function(){Ky(d);throw a;})})}).catch(function(a){c.m.error("Failed to start remoting streams",a);az(c);return{audio_stream_id:-1,video_stream_id:-1}})};
$y.prototype.startDataStreams=$y.prototype.cq;$y.prototype.stop=function(a){var b=this;Hy(this.j,function(c){b.b.onStopped(a);return dz(b).then(function(){b.m.info("Remoting stopped.");Ky(c,5);(0,b.l)().then(function(){return Gy(b.j,5,function(a){if(b.b&&b.f)b.b.onSinkAvailable(b.C);Ky(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.m.error("Failed to stop remoting: ",a);az(b)})};$y.prototype.stop=$y.prototype.stop;
$y.prototype.On=function(){null===this.s&&(this.s=te(this.A.hc.Qf).then(function(a){return a.f||!1}));return this.s.then(function(a){return{rate:(a?1E7:5E6)/8}})};$y.prototype.estimateTransmissionCapacity=$y.prototype.On;
var dz=function(a){return a.D.stop().then(function(){Cy(a.B,"RPC");iz(a.h);jz(a.h)})},bz=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.m.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.m.error("Pref value not a boolean: "+JSON.stringify(c)):(a.f=!!c.value,a.m.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)||chrome.settingsPrivate.onPrefsChanged.addListener(a.o);b()})})};
$y.prototype.R=function(a){if(this.b){a=la(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.m.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.f==a)break;this.f=a;this.m.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.C);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Yy=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.bq||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,k=d.video_capabilities,m=b.Zd||"";(a.b||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.m.info("Unknown mediaCap name: "+a)}});b.Zd&&"Chromecast Ultra"==b.Zd&&k.push(f.SUPPORT_4K);return d},Zy=function(){this.l=this.j=this.b=null;this.s=this.f=this.A=this.h=this.o=0;this.g=null},gz=function(a){a.b=[];kz(a,performance.now())},hz=function(a,b,c){a.j=b;a.l=
c;a.b?(b=a.b,a.b=null,b.forEach(function(b){return ez(a,b.data).then(b.Np,b.bl)})):kz(a,performance.now())},iz=function(a){if(a.b){var b=Error("Stop before delivering pending message");a.b.forEach(function(a){return a.bl(b)});a.b=null}a.j=null;a.l=null},ez=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.o;a.h+=b.length;return a.j({type:"RPC",rpc:c})}return a.b?new Promise(function(c,e){a.b.push({data:b,Np:c,bl:e})}):Promise.reject(Error("RPC pipe not started"))},fz=function(a,
b){jz(a);a.g=setInterval(function(){if(a.b)var c=a.b.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.s)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec) and ")+("received "+a.A+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";kz(a,c);c=d}b(c)},3E4)},jz=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},kz=function(a,b){a.o=0;a.h=0;a.A=0;a.f=0;a.s=b};var lz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},mz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var nz=function(a,b,c,d,e){this.h=new Ny(a,b,c,d,void 0===e?null:e);this.m=db("mr.mirror.cast.MediaStreamer");this.j=new Ey;this.g=this.f=this.b=this.l=null};nz.prototype.start=function(a,b){var c=this;return Gy(this.j,1,function(d){c.l=a;c.b=lz(a);c.b&&"ended"==c.b.readyState&&(c.b=null);c.f=mz(a);c.f&&"ended"==c.f.readyState&&(c.f=null);if(!c.b&&!c.f)return Ky(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.h.start(c.b,c.f,c.g).then(function(){return Ky(d,2)})})};
nz.prototype.stop=function(){var a=this;return Iy(this.j,function(b){return a.h.stop().then(function(){a.b=null;a.f=null;a.l=null;a.g=null;Ky(b,1)})})};var oz=function(a){return Gy(a.j,2,function(b){a.m.info("Suspending media streaming...");return a.h.stop().then(function(){a.m.info("Suspended media streaming.");Ky(b,3)})})};
nz.prototype.resume=function(){var a=this;return Gy(this.j,3,function(b){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.m.info("Resuming media streaming...");return a.h.start(a.b,a.f,a.g).then(function(){a.m.info("Resumed media streaming.");Ky(b,2)})})};var pz=function(a,b,c){this.j=a;this.g=b;this.h=c;this.m=db("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};pz.prototype.start=function(){var a=this;null==this.b&&(jb(this.m,"Starting Wifi Status Monitoring."),this.f=[],By(this.h,"STATUS_RESPONSE",function(b){return qz(a,b)}),this.b=setInterval(function(){return rz(a)},12E4),rz(this))};pz.prototype.stop=function(){null!=this.b&&(jb(this.m,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,Cy(this.h,"STATUS_RESPONSE"))};
var qz=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.b&&(c.wifiSnr=b.status.b);null!=b.status.f&&(c.wifiSpeed=b.status.f[3]);0==Object.keys(c).length?v(a.m,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(c),a.m.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else v(a.m,function(){return"Ignoring response without status: "+JSON.stringify(b)})},rz=function(a){a.h.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:gl(a.g),get_status:["wifiSnr","wifiSpeed"]})};var sz=function(a,b,c,d){this.C=b.Qf;this.A={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Eg(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Zd};this.F=c;this.B=d;this.g=this.f=this.o=this.l=this.j=this.s=this.h=null;this.b=[]};sz.prototype.jf=function(a){null!=this.f&&clearInterval(this.f);this.h=a;this.s=Date.now();this.f=setInterval(this.w.bind(this,a),9E5)};
sz.prototype.Tf=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.h){var a=this.w(this.h);this.h=null;return a}return Promise.resolve()};sz.prototype.Qd=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.l=a():"string"===typeof a&&(this.l=a),b&&"string"===typeof b.stack&&(this.o=b.stack))};
var uz=function(a,b){return(null==a.h?Promise.resolve():a.w(a.h)).then(function(){var c=b.map(function(b){b=tz(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.Oe}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),Oe:new Blob(d,{type:"application/json"})}});a.b=[];return c})};
sz.prototype.w=function(a){var b=this;if(null!=this.g)return this.g;var c=te(this.C).then(function(c){c={receiverVersion:c.b,receiverConnected:c.g,receiverOnEthernet:c.f,receiverHasUpdatePending:c.h,receiverUptimeSeconds:c.j};Object.assign(c,b.A);var d=Date.now();Object.assign(c,{startTime:b.s,endTime:d,activity:Py(a),receiverWifiStatus:Array.from(b.B.f)});b.s=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.l,streamingErrorCause:b.o}),b.j=null,b.l=null,b.o=null);return c});
return(this.g=Promise.all([c.then(function(b){return Vy(a,b)}),c,Wy(a)]).then(function(a){var c=la(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.b.push({events:a,Oe:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.b=tz(b,b.F);b.g=null}))||Promise.resolve()};
var tz=function(a,b){b-=2;for(var c=[],d=a.b.length-1;0<=d;--d){b-=a.b[d].Oe.size+1;if(0>b)break;c.push({events:null,Oe:a.b[d].Oe});if(null!=a.b[d].events){var e=a.b[d].events.size;b>=e&&(c[c.length-1].events=a.b[d].events,b-=e)}}return c.reverse()};var vz=db("mr.NetworkUtils"),wz=function(a,b){return Hf?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(v(vz,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(vz.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var xz=function(a,b,c,d){d=void 0===d?null:d;Bg.call(this,b);var e=b.hc;this.w=e.sessionId;this.D=e.Qf;this.C=a;this.ja=d;this.m=db("mr.mirror.cast.Session");this.s=new Ey;this.o=new fl("mirror.cast.SeqNumGenerator");this.A=new Ay(b.id);this.l=new nz(e,this.C,this.o,this.A,this.ja);this.j=null;this.b=new sz(a,e,c,new pz(this.w,this.o,this.A));this.f=!1;this.F=null};l(xz,Bg);g=xz.prototype;
g.start=function(a){var b=this;return Gy(this.s,1,function(c){var d=new nb("MediaRouter.CastStreaming.Session.Launch");return yz(b).then(function(c){b.f=c;return b.l.start(a,b)}).then(function(){if(b.l.h.B){var a=b.b;a.A.tdlsIsOn=b.f;a.B.start();zz(b)}else b.b.A.tdlsIsOn=b.f;d.b();b.F=new tb("MediaRouter.CastStreaming.Session.Length");Ky(c,2);return b})})};
g.stop=function(){var a=this;return Iy(this.s,function(b){a.F&&(a.F.b(),a.F=null);a.b.B.stop();return a.l.stop().then(function(){return a.j?az(a.j):Promise.resolve()}).then(function(){a.j=null;return a.f?Az(a):Promise.resolve()}).then(function(){a.f=!1;Ky(b,4)})})};g.Zk=function(){var a={sessionId:this.w,seqNum:gl(this.o),type:"PRESENTATION",icons:[],title:zg(this.g)};this.m.info("Sending session metadata update to receiver: "+this.w);this.A.sendMessage(a)};g.jf=function(a){this.b.jf(a)};g.Tf=function(){return this.b.Tf()};
g.Qd=function(a,b){this.b.Qd(a,b);this.m.error(a,b);this.stop()};
var Bz=function(a,b){return uz(a.b,b)},yz=function(a){return a.C.useTdls?wz(a.D,!0).then(function(b){if("Connected"==b)return a.m.info("Successfully enabled TDLS."),!0;v(a.m,"Did not enable TDLS: result="+b);return!1}).catch(function(b){v(a.m,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Az=function(a){return wz(a.D,!1).catch(function(b){return a.m.error("Error while turning TDLS back off",b)})},zz=function(a){Cz(a).then(function(b){(b.b||[]).includes("video")?Dz(a,b):v(a.m,
function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){v(a.m,"None/Invalid capabilites response. Media Remoting disabled.",b)})},Cz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.w,seqNum:gl(a.o)};a.m.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Dy(a.A,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.m.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;jb(a.m,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Dz=function(a,b){Gy(a.s,2,function(c){var d=a.h.hc.Zd||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return v(a.m,"HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
Ky(c),Promise.resolve();a.j=new $y(a.h,b,a.C,a.o,a.A,a.ja);return cz(a.j,a.L.bind(a),a).catch(function(b){a.m.error("Media Remoting start failed: "+b.message,b)}).then(function(){return Ky(c)})})};xz.prototype.L=function(){var a=this;return Gy(this.s,2,function(b){return new Promise(function(c,d){oz(a.l).then(function(){Ky(b,3);a.R=!0;wg(a);c(a.S.bind(a))}).catch(function(b){a.Qd("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
xz.prototype.S=function(){var a=this;return Gy(this.s,3,function(b){return new Promise(function(c,d){a.l.resume().then(function(){Ky(b,2);a.R=!1;wg(a);c()}).catch(function(b){a.Qd("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Ez=function(){pg.call(this,"cast_streaming")};l(Ez,pg);g=Ez.prototype;g.getName=function(){return"cast_streaming"};g.lg=function(a,b){return new xz(a,b,20969472,null)};g.Wg=function(){ay(0)};g.Tg=function(){ay(1)};g.mi=function(){ay(2)};g.Ug=function(){wb("MediaRouter.CastStreaming.Session.End")};g.Vg=function(a){xb("MediaRouter.CastStreaming.Start.Failure",a,Df)};g.Kf=function(){wb("MediaRouter.CastStreaming.Stream.End")};
g.kh=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&hy(),e=[9351424];d&&e.push(20969472);return Bz(a,e).then(function(a){var e=a[a.length-1];a=gj(a[0].events).catch(function(a){b.J.error("Failed to persist events Blob.",a)});d&&0<e.events.size?dy(e.events,void 0,b.Bo.bind(b)):c&&cy("stats.json",e.Oe,void 0,void 0);return a})})};g.Bo=function(a){a&&(gy().b=Date.now())};
g.Vh=function(a){this.J.info("Received message to upload logs for "+a);return this.b?Bz(this.b,[20969472]).then(function(b){b=la(b).next().value;return 0==b.events.size?"":dy(b.events,a)}):Promise.resolve(Fz(this,a))};
var Fz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return gj(new Blob),a.J.info("Uploading saved logs for feedback."),dy(c,b)},Gz=new Ez;eg("mr.mirror.cast.Service",Gz);
